# Form implementation generated from reading ui file 'src/vista/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 200)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        self.menuCalculo_de_Areas = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculo_de_Areas.setObjectName("menuCalculo_de_Areas")
        MainWindow.setMenuBar(self.menubar)
        self.actionSeleccionarFigura = QtGui.QAction(parent=MainWindow)
        self.actionSeleccionarFigura.setObjectName("actionSeleccionarFigura")
        self.actionCirculo = QtGui.QAction(parent=MainWindow)
        self.actionCirculo.setObjectName("actionCirculo")
        self.actionTriangulo = QtGui.QAction(parent=MainWindow)
        self.actionTriangulo.setObjectName("actionTriangulo")
        self.actionRectangulo = QtGui.QAction(parent=MainWindow)
        self.actionRectangulo.setObjectName("actionRectangulo")
        self.actionCuadrado = QtGui.QAction(parent=MainWindow)
        self.actionCuadrado.setObjectName("actionCuadrado")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuCalculo_de_Areas.addAction(self.actionSeleccionarFigura)
        self.menubar.addAction(self.menuCalculo_de_Areas.menuAction())
        self.menubar.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora de Áreas"))
        self.menuCalculo_de_Areas.setTitle(_translate("MainWindow", "Cálculo de Áreas"))
        self.actionSeleccionarFigura.setText(_translate("MainWindow", "Seleccionar Figura"))
        self.actionSeleccionarFigura.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCirculo.setText(_translate("MainWindow", "Circulo"))
        self.actionTriangulo.setText(_translate("MainWindow", "Triangulo"))
        self.actionRectangulo.setText(_translate("MainWindow", "Rectangulo"))
        self.actionCuadrado.setText(_translate("MainWindow", "Cuadrado"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
